name: Deploy Infractructure
run-name: ${{ github.actor }} has triggered the pipeline

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Select service to deploy"
        required: true
        type: choice
        options:
          - option1
          - option2
          - option3

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_PROFILE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize
        run: |
          echo "Selected service: ${{ github.event.inputs.SERVICE }}"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Intsall Python Fromatter (black)
        run: |
          pip install black

      - name: Clean up
        run: |
          rm -rf terraform.zip
          rm -rf ${{ github.workspace }}/tmp
